name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-compose-action@v1
        with:
          version: latest
      - uses: astral-sh/setup-uv@v7
      - run: uv sync
      - run: docker-compose -f docker-compose.test.yml up -d
      - run: uv run pytest -v
